title: "&cMy Menu"
allow-dragging: false
allow-under-inventory-interact: true
creation-data:
  - "x red orange yellow green light_blue magenta purple x"
  - "red orange foo yellow bar light_blue baz magenta purple"
  - "x red orange yellow green light_blue magenta purple x"